name: Semgrep

on:
  pull_request: {}

  push:
    branches: ["master"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
      # volumes:
      #   - ${{ github.workspace }}:/host

    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: Ayrx/semgrep-rules
          ssh-key: ${{ secrets.semgrep_rules_deploy_key }}

      - run: semgrep ci
        env:
          SEMGREP_RULES: ${{ github.workspace }}/semgrep-rules/rules
